version: 2.1

jobs:

  validate-environment:
    working_directory: ~/repo
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Validate environment
          command: |
            apk add yq
            sh ./scripts/validate-env.sh "./.circleci/config.yml" "staging" "prod"

  staging:
    working_directory: ~/repo
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Running staging
          command: |
            echo "Staging migration"
    environment:
      - GOOGLE_PROJECT_ID: staging-proj
      - GOOGLE_COMPUTE_ZONE: staging-zone
      - ENV: staging_migration


  prod:
    working_directory: ~/repo
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Running production
          command: |
            echo "Production migration"
    environment:
      - GOOGLE_PROJECT_ID: prod-project
      - GOOGLE_COMPUTE_ZONE: prod-zone
      - ENV: prod_migration



workflows:

  service:
    jobs:
      - validate-environment
      - staging:
          requires:
            - validate-environment
      - prod:
          requires:
            - staging
